---
- hosts: worker
  remote_user: root

  tasks:
  - name: update pods per core
    replace:
      path: /etc/cfc/kubelet/kubelet-service-config
      regexp: 'podsPerCore: 10'
      replace: 'podsPerCore: 30'
  - name: restart the kubelet
    command: systemctl restart kubelet